#!/bin/bash

#SBATCH --job-name=bwa-mem   ## Name of the job
#SBATCH -A ecoevo282         ## account to charge 
#SBATCH -p standard          ## partition/queue name
#SBATCH --nodes=1            ## (-N) number of nodes to use
#SBATCH --ntasks=1           ## (-n) number of tasks to launch
#SBATCH --cpus-per-task=32    ## number of cores the job needs
#SBATCH --error=slurm-%J.err ## error log file
#SBATCH --array=0-9     ## submit 16 jobs to iterate over

module load bwa

threads=32
PROJECTDIR=/data/class/ecoevo282/swdu/ee282/project
REF=${PROJECTDIR}/reference/Mus_musculus.GRCm38.dna.toplevel.fa.gz
READPATH=${PROJECTDIR}/data/rawdata/
R1=${READPATH}SRR1214840${SLURM_ARRAY_TASK_ID}_1.fastq.gz
R2=${READPATH}SRR1214840${SLURM_ARRAY_TASK_ID}_2.fastq.gz

module load bwa

bwa mem -t $threads $REF $R1 $R2 > \
${PROJECTDIR}/data/processed/SRR121484_${SLURM_ARRAY_TASK_ID}.sam
